
CREATE TABLE public.products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  image_url text,
  gallery text[] NOT NULL DEFAULT '{}',
  short_description text,
  price numeric(12,2) NOT NULL DEFAULT 0,
  promo_price numeric(12,2),
  stock integer NOT NULL DEFAULT 0,
  product_cost numeric(12,2) NOT NULL DEFAULT 0,
  delivery_cost numeric(12,2) NOT NULL DEFAULT 0,
  provinces text[] NOT NULL DEFAULT '{}',
  cities text[] NOT NULL DEFAULT '{}',
  delivery_time text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.team_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  role text NOT NULL DEFAULT 'operador' CHECK (role IN ('administrador','operador','gestor','entregador')),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number bigint GENERATED BY DEFAULT AS IDENTITY,
  product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  unit_price numeric(12,2) NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  delivery_cost numeric(12,2) NOT NULL DEFAULT 0,
  total numeric(12,2) NOT NULL DEFAULT 0,
  customer_name text NOT NULL,
  phone text NOT NULL,
  province text NOT NULL,
  city text NOT NULL,
  neighborhood text NOT NULL,
  reference_point text,
  contact_period text,
  contact_slot text,
  status text NOT NULL DEFAULT 'nova' CHECK (status IN ('nova','por_ligar','agendada','nao_atende','numero_invalido','confirmada','preparacao','em_entrega','entregue','cancelada','recusada','reagendar')),
  assignee text,
  cancel_reason text,
  callback_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_orders_phone ON public.orders(phone);
CREATE INDEX idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX idx_orders_product_id ON public.orders(product_id);

CREATE TABLE public.order_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  content text NOT NULL,
  author text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_order_notes_order_id ON public.order_notes(order_id);

CREATE TABLE public.order_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  description text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_order_events_order_id ON public.order_events(order_id);

GRANT SELECT ON public.products TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO authenticated;
GRANT ALL ON public.products TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_members TO authenticated;
GRANT ALL ON public.team_members TO service_role;

GRANT INSERT ON public.orders TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders TO authenticated;
GRANT ALL ON public.orders TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_notes TO authenticated;
GRANT ALL ON public.order_notes TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_events TO authenticated;
GRANT ALL ON public.order_events TO service_role;

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view active products" ON public.products FOR SELECT TO anon USING (active = true);
CREATE POLICY "Team can view products" ON public.products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Team can manage products" ON public.products FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Team can manage team members" ON public.team_members FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Public can create orders" ON public.orders FOR INSERT TO anon WITH CHECK (status = 'nova');
CREATE POLICY "Team can manage orders" ON public.orders FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Team can manage notes" ON public.order_notes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Team can manage events" ON public.order_events FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

CREATE TRIGGER products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.log_order_event()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.order_events(order_id, description) VALUES (NEW.id, 'Encomenda criada');
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.order_events(order_id, description)
    VALUES (NEW.id, 'Estado alterado para ' || NEW.status || COALESCE(' - ' || NEW.cancel_reason, ''));
    IF NEW.status = 'entregue' AND OLD.status <> 'entregue' THEN
      UPDATE public.products SET stock = GREATEST(stock - NEW.quantity, 0) WHERE id = NEW.product_id;
    END IF;
  END IF;
  RETURN NEW;
END; $$;

CREATE TRIGGER orders_log_insert AFTER INSERT ON public.orders FOR EACH ROW EXECUTE FUNCTION public.log_order_event();
CREATE TRIGGER orders_log_update AFTER UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.log_order_event();

CREATE OR REPLACE FUNCTION public.get_order_receipt(p_id uuid)
RETURNS TABLE (
  id uuid, order_number bigint, product_name text, quantity integer,
  unit_price numeric, delivery_cost numeric, total numeric,
  customer_name text, phone text, province text, city text,
  neighborhood text, reference_point text, created_at timestamptz
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT o.id, o.order_number, o.product_name, o.quantity, o.unit_price, o.delivery_cost,
         o.total, o.customer_name, o.phone, o.province, o.city, o.neighborhood,
         o.reference_point, o.created_at
  FROM public.orders o WHERE o.id = p_id;
$$;
GRANT EXECUTE ON FUNCTION public.get_order_receipt(uuid) TO anon, authenticated;

ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_notes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
