ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS timer_minutes INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS timer_seconds INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS timer_color TEXT DEFAULT '#ef4444';